### ISSUE TITLE
Data submission to Pulsar: data from Texas

### ISSUE THREAD

**Issue by AnnikaWeimer** [nathankw/pulsar_lims#124]
https://docs.google.com/spreadsheets/d/1kFFz-S8vCklSSekGcD3tR8DjrESNiQPL/edit#gid=1006123213

Hi Tao, we received 84 biosamples today from collaborators in Texas. They are already on the portal but we need them in Pulsar. I added a tab (2nd) to the spreadsheet above with all information needed. Could you submit those to Pulsar?

Urgency: not the most urgent thing to do but it would be good to have them there within the next 2 weeks. Thanks!

**Comment by twang15** [comment]
@twang15

**Comment by twang15** [comment]
Submission done

**Comment by twang15** [comment]
Hi Annika,
 
I see it and will take care of it asap and within the time frame you listed.
In the future, you can add others too.
I regularly scan the issue list, so that I can know any new ones in time.
 
Best,
Tao

**Comment by twang15** [comment]
Hi Annika,
 
This dataset has been submitted to Pulsar.
 
Best,
Tao

**Comment by twang15** [comment]
notification done

**Comment by AnnikaWeimer** [comment]
@twang15  Thank you!!

**Comment by AnnikaWeimer** [comment]
Thanks!
__________________________________________

Annika K. Weimer, PhD
Project Lead ENCODE - Snyder lab

Stanford Medicine – Department of Genetics
Center for Genomics and Personalized Medicine

***@***.******@***.***>
+1 ‭(650) 724-4044

On Mar 22, 2021, at 9:10 AM, twang15 ***@***.******@***.***>> wrote:



Closed #124<https://github.com/nathankw/pulsar_lims/issues/124>.
