### ISSUE TITLE
Data submission to ENCODE: cs-393

### ISSUE THREAD

**Issue by AnnikaWeimer** [nathankw/pulsar_lims#160]
https://www.encodeproject.org/experiments/ENCSR286OIN/

There are a few things that have to be fixed here:
1) Biosample summary: not sure where the NONE comes from in the text
2) One of the biosamples doesn't have a GM
3) This ChIP says that it's HEY2 but it's actually JAZF1 (Cory mislabeled the tubes!!!!) --> we can delete the fastqs here and submit them as JAZF1 (the real HEY2 is being sequences at the moment)?
@twang15

**Comment by twang15** [comment]
This is in fact a duplicate of #127
