### ISSUE TITLE
Data submission to Pulsar: biosample from JAX lab

### ISSUE THREAD

**Issue by AnnikaWeimer** [nathankw/pulsar_lims#200]
Hi Tao, we will receive biosamples from the JAX lab next week. They are already registered on the portal but not on pulsar. I added all information to this spreadsheet (3rd tab). Could you submit them to pulsar?
It's not the most urgent thing this week.

@twang15 

Thanks, Annika 
[Stanford Shipment - Snyder -March2021_BL_2.xlsx](https://github.com/nathankw/pulsar_lims/files/6246378/Stanford.Shipment.-.Snyder.-March2021_BL_2.xlsx)

**Comment by twang15** [comment]
Here is the shared version to work on:
https://docs.google.com/spreadsheets/d/1B2E9fRSCNxXY8Iw0DL4zSR0zm0mH9taB/edit#gid=1273715014

**Comment by twang15** [comment]
submission done

**Comment by twang15** [comment]
Hi Annika,

The submission has been finished.
Please check it out here:
https://docs.google.com/spreadsheets/d/1B2E9fRSCNxXY8Iw0DL4zSR0zm0mH9taB/edit#gid=1273715014

Best,
Tao
