### ISSUE TITLE
IP submission to ENCODE: CS-370

### ISSUE THREAD

**Issue by twang15** [nathankw/pulsar_lims#89]
For CS-368's biosamples, each biosample has an IP (share the same gel image but in different lanes), and each biosample gets one copy of the same gel image on the portal (see https://www.encodeproject.org/experiments/ENCSR125YGM/).

For CS-370, no biosample has an IP. Instead, their parent has an IP image in lane 2, which has been submitted, see
https://www.encodeproject.org/biosamples/ENCBS143BQE/ and cannot be submitted again without modifying the submission code.

Questions:
1. Why is it different from that of CS-368?
2. Do we need to attach a copy for each replicate in CS-370? https://www.encodeproject.org/experiments/ENCSR062GGC/

If for CS-370 and other similar cases, children biosamples really share the same IP and in the same lane as their parent, the solution is to submit one IP for each biosample. Otherwise, the submission will fail.

**Comment by AnnikaWeimer** [comment]
Hi Tao, how often do you come across these cases? I think the problem is is that the validations are very old and at that time there was only one IP for all the biosamples. We should submit the same image to both biosamples on the portal then. If I remember correctly we did that before with some IPs from Chicago?

**Comment by twang15** [comment]
I saw them several times.
It is just confusing to me how to solve it automatically.
I try to figure out a basic standard for both IP and PCR.

**Comment by twang15** [comment]
The two IPs are uploaded semi-automatically by fixing the code and manipulating pulsar temporarily.
